// BENCH/WEB/reactjs/src/App.js
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import React from "react";
import LoginPage from "./Login";
import HomePage from "./Home";
import ForgotPwdPage from "./ForgotPwd";

function App() {

    return (
        <Router>
            <Routes>
                <Route path="/" element={<LoginPage />} />
                <Route path="/home" element={<HomePage />} />
                <Route path="/forgotPwd" element={<ForgotPwdPage />} />
            </Routes>
        </Router>
    );
}

export default App;

// BENCH/WEB/Svelte/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { navigate, Router, Route} from 'svelte-routing';
  import LoginPage from './routes/LoginPage.svelte';
  import HomePage from './routes/HomePage.svelte';
  import ForgotPassword from './routes/ForgotPassword.svelte'

  onMount(() => {
    navigate('/');
  });
</script>

<Router>
  <Route path="/" component={LoginPage} />
  <Route path="/home" component={HomePage}/>
  <Route path="/forgotPassword" component={ForgotPassword}/>
</Router>
